extra_queries/config/routes.rb
get 'projects/:project_id/extra_queries/add_filter(/:query_id)', to: 'extra_queries#add_filter'

resources :query_categories do
  collection do
    post 'create_of_query', to: 'query_categories#create_of_query'
    post 'move_position', to: 'query_categories#move_position'
  end
end

get 'extra_queries/add_filter(/:query_id)', to: 'extra_queries#add_filter'
post 'extra_queries/pinning/:query_id', to: 'extra_queries#pinning'
get 'extra_queries/query_group/:query_group(/:project_id)', to: 'extra_queries#query_group'
post 'extra_queries/pinned_queries_order', to: 'extra_queries#pinned_queries_order'

extra_queries/app/models/eq_pinned_query.rb
class EqPinnedQuery < ActiveRecord::Base
  belongs_to :issue_query, foreign_key: :query_id
  belongs_to :user

  attr_protected :id
end

extra_queries/app/models/query_category.rb
class QueryCategory < ActiveRecord::Base
  has_many :query, foreign_key: :category_id, dependent: :nullify
  belongs_to :user, foreign_key: :author_id

  attr_protected :id
end

extra_queries/app/controllers/extra_queries_controller.rb
class ExtraQueriesController < ApplicationController
  before_action :find_optional_project, only: [:add_filter]

  include IssuesHelper
  helper ExtraQueries::Helpers::IssuesExtendHelper

  def add_filter
    @fields = params[:fields]

    if params[:query_id].present?
      @query = Query.find(params[:query_id])
    else
      @query = Query.new_subclass_instance(params[:type] || 'IssueQuery', { project: @project, name: '_' })
    end

    if @project.present?
      @query.project = @project
    end
  end

  def pinning
    @query = Query.find(params[:query_id])
    if params[:pin]
      @query.eq_user_pinned_query ||= EqPinnedQuery.new(user_id: User.current.id, position: EqPinnedQuery.where(user_id: User.current.id).order("#{EqPinnedQuery.table_name}.position desc").first.try(:position).to_i + 1)
    else
      @query.eq_user_pinned_query.try(:destroy)
    end
  end

  def query_group
    @klass = case params[:type]
               when 'timelog' then TimeEntryQuery
               else IssueQuery
             end
    @project = Project.find(params[:project_id]) if params[:project_id]
    if params[:query_group] == 'queries'
      session[:eq_queries_expanded] = params[:status]
    elsif params[:query_group] == 'categories'
      session[:eq_queries_by_category_expanded] = params[:status]
    elsif params[:query_group] == 'queries_by_role'
      session[:eq_queries_by_role_expanded] = params[:status]
    end

    if params[:expand]
      render layout: false
    else
      render nothing: true
    end
  end

  def pinned_queries_order
    queries_ids = params['pinned-query']
    queries = Query.preload(:eq_user_pinned_query).where(id: queries_ids + [0]).to_a
    queries_ids.each_with_index do |q, index|
      q = queries.select { |it| it.id == q.to_i }.first
      next unless (q)
      q.eq_user_pinned_query ||= EqPinnedQuery.new(user_id: User.current.id)
      q.eq_user_pinned_query.position = index
      q.eq_user_pinned_query.save
    end

    render nothing: true
  end

  private

  def sidebar_queries(query_type)
    @project = Project.find(params[:project_id]) unless params[:project_id].blank?

  end

  def find_optional_project
    @project = Project.find(params[:project_id]) unless params[:project_id].blank?
  rescue ActiveRecord::RecordNotFound
    render_404
  end
end

extra_queries/app/controllers/query_categories_controller.rb
class QueryCategoriesController < ApplicationController
  self.main_menu = false
  before_action :require_login
  before_action :authorized_globaly?
  before_action :find_query_category, except: [:index, :new, :create, :create_of_query, :move_position]

  def index
    @query_categories = QueryCategory.order(:position)
  end

  def new
    @query_category = QueryCategory.new
    render partial: 'form'
  end

  def edit
    render partial: 'form'
  end

  def update
    @query_category.update_attributes(params[:query_category])
  end

  def create
    @query_category = QueryCategory.create(name: params[:query_category][:name], author_id: User.current.id, position: QueryCategory.order(:position).last.try(:position).to_i + 1)
  end

  def create_of_query
    category = QueryCategory.create(name: params[:name], author_id: User.current.id, position: QueryCategory.order(:position).last.try(:position).to_i + 1)
    render json: { id: category.id, name: category.name }
  end

  def move_position
    qc = QueryCategory.find(params[:query_category_id])
    if params[:new_position].to_i + 1 > qc.position
      QueryCategory.where('position > ? and position <= ?', qc.position, params[:new_position].to_i + 1).update_all('position = position - 1')
    elsif params[:new_position].to_i + 1 < qc.position
      QueryCategory.where('position < ? and position >= ?', qc.position, params[:new_position].to_i + 1).update_all('position = position + 1')
    end
    qc.update_attributes(position: params[:new_position].to_i + 1)

    if request.xhr?
      render nothing: true
      return
    end

    redirect_to action: 'index'
  end

  def destroy
    @query_category.destroy
  end

  private

  def find_query_category
    @query_category = QueryCategory.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    render_404
  end

end

extra_queries/app/views/extra_queries/_filter_selector.html.erb
<% items = [] if items.blank?
   selected = (options[:selected] || []).map(&:to_s)
%>
<div class="<%= options[:class] %>">
  <div class="eq-filter-search">
    <%= text_field_tag 'eq-search', '', placeholder: l(:eq_label_search_placeholder) , id: nil, class: 'eq-search' %>
  </div>
  <div class="eq-filter-list-container">
    <ul<%= field || options[:id] ? " id='#{options[:id] ? options[:id] : "eq-filter-list-#{field}"}'".html_safe : '' %> class="eq-filter-list">
      <li class="eq-filter-list-custom-actions eq-no-matches-ajax eq-out-search">
        <span class="eq-init-msg"><%= l(:eq_label_no_matches_ajax) %></span>
        <span class="eq-search-msg" style="display:none;"><%= l(:eq_label_searching_ajax) %></span>
      </li>
      <li class="eq-filter-list-custom-actions eq-no-matches eq-out-search">
        <%= l(:eq_label_no_matches) %>
      </li>
      <li class="eq-filter-list-custom-actions eq-clear-filter eq-out-search">
        <%= link_to l(:eq_label_clear_selected_values), '#', class: 'in_link eq-filter-list-clear' %>
      </li>
      <% items.each do |it| %>
        <% it = it.is_a?(Array) ? it : [it, it] %>
        <% if it[2].is_a?(Hash) && it[2][:group_title] %>
          <li class="eq-filter-list-group">
            <%= it[0] %>
          </li>
        <% else %>
          <li class="eq-filter-list-item"<%= it[2] && it[2].is_a?(Hash) && it[2][:hide] ? ' style="display:none;"'.html_safe : '' %>>
            <label>
              <% if options[:radio] %>
                <%= radio_button_tag options[:fullname] || "eq-values#{options[:name]}[]", it[1], selected.include?(it[1].to_s), id: "eq-value-#{field}-#{it[1]}", class: 'eq-value' %>
              <% else %>
                <%= check_box_tag options[:fullname] || "eq-values#{options[:name]}[]", it[1], selected.include?(it[1].to_s), id: "eq-value-#{field}-#{it[1]}", class: 'eq-value' %>
              <% end %>

              <% if it[2].is_a?(Hash) && it[2][:object].present? && it[2][:object].respond_to?(:render_query_filter_item) %>
                <%= it[2][:object].render_query_filter_item(self) do |name| %>
                  <span class="eq-value-text" data-text="<%= it[0] %>"><%= name %></span>
                <% end %>
              <% else %>
                <span class="eq-value-text" data-text="<%= it[0] %>"><%= it[0] %></span>
              <% end %>
              <%= yield(it) if block_given? %>
            </label>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

extra_queries/app/views/extra_queries/_filters.html.erb
<% query ||= @query %>

<div id="eq-filters">
  <table class="eq-filters-table">
    <tr>
      <td>
        <div class="eq-default">
          <% query.eq_filters.select { |k,v| v.eq_default }.each do |k, v| %>
            <%= eq_render_filter_field(query, k, v) %>
          <% end %>
        </div>
        <div class="eq-user">
          <% query.eq_filters.select { |k,v| !v.eq_default }.each do |k, v| %>
            <%= eq_render_filter_field(query, k, v) %>
          <% end %>
        </div>
      </td>
      <td style="width: 1px; vertical-align: top;">
        <%= link_to '', '#', id: 'f-fields-list', class: 'eq-fields-button', title: l(:label_filter_add), data: { field: 'fields-list', url: url_for(controller: :extra_queries, action: :add_filter, query_id: params[:query_id], type: query.type) } %>
        <div class='modal_window eq-fields-list' id='modal-f-fields-list' style="padding-top: 10px;">
          <div class="eq-filter-data">
            <div class="eq-filter-data-list eq-filter-data-item">
              <%= eq_filter_selector(query.available_filters.map { |field, field_options| [query.label_for(field), field] }.sort { |x,y| (x[0] || '') <=> (y[0] || '') }) %>
            </div>
          </div>
        </div>
      </td>
    </tr>
  </table>
</div>

<%= render partial: "#{controller_name}/eq_filter_params", locals: { query: query } rescue '' %>

extra_queries/app/views/extra_queries/_rmplus_logo.html.erb
<% path_array = File.dirname(__FILE__).split('/') %>
<% plugin_name = path_array.fetch(path_array.index('plugins') + 1) %>

<div id="rmplus-logo" style="text-align: left; margin-top: 10px;">
  <div>
    <%= image_tag 'logo.png', plugin: plugin_name, alt: l(:label_rmplus_logo), title: l(:label_rmplus_logo), width: 50, style: 'vertical-align: bottom;' %>
    <span style="font-size: 10pt; margin-left: 5px;">
      <%= l(:label_rmplus_logo) %>&nbsp<a href="http://rmplus.pro">http://rmplus.pro</a>.
    </span>
  </div>
</div>

extra_queries/app/views/extra_queries/_settings.html.erb
<%
  query = IssueQuery.new
  filter_fields = [[l(:field_assigned_to), :assigned_to_id], [l(:field_author), :author_id]]
  filter_fields += IssueCustomField.where("field_format = 'user'").order('name').collect { |cf| [cf.name, "cf_#{cf.id}"] }
%>
<table class="plugin_settings" style="width: 100%">
  <tr>
    <td></td>
    <td>
      <label for='settings_custom_query_page_enabled'>
        <%= check_box_tag 'settings[custom_query_page_enabled]', 1, @settings['custom_query_page_enabled'] %>
        &mdash;
        <%= l(:eq_settings_custom_query_page_enabled) %>
      </label>
    </td>
  </tr>

  <tr>
    <td></td>
    <td>
      <label for='settings_custom_query_timelog_page_enabled'>
        <%= check_box_tag 'settings[custom_query_timelog_page_enabled]', 1, @settings['custom_query_timelog_page_enabled'] %>
        &mdash;
        <%= l(:eq_settings_custom_query_timelog_page_enabled) %>
      </label>
    </td>
  </tr>

  <tr>
    <td></td>
    <td>
      <label for='settings_custom_query_sidebar_enabled'>
        <%= check_box_tag 'settings[custom_query_sidebar_enabled]', 1, @settings['custom_query_sidebar_enabled'] %>
        &mdash;
        <%= l(:eq_settings_custom_query_sidebar_enabled) %>
      </label>
    </td>
  </tr>

  <tr>
    <td>
      <label for='settings_default_filter_fields'><%= l(:eq_settings_default_filter_fields) %></label>
    </td>
    <td>
      <%= select_tag 'settings[default_filter_fields][]', options_for_select(query.all_available_filters.map { |k, v| [v[:name], k] }, @settings['default_filter_fields']), multiple: true, size: 8, class: 'select2' %>
    </td>
  </tr>

  <tr>
    <td></td>
    <td>
      <label for='settings_eq_sub_issues_extra_subject'>
        <%= check_box_tag 'settings[eq_sub_issues_extra_subject]', 1, @settings['eq_sub_issues_extra_subject'] %>
        &mdash;
        <%= l(:eq_settings_eq_sub_issues_extra_subject) %>
      </label>
    </td>
  </tr>

  <tr>
    <td></td>
    <td id="settings_save_button">
      <%= render file: File.join(File.dirname(__FILE__), "_rmplus_logo.html.erb") %>
    </td>
  </tr>
</table>

extra_queries/app/views/extra_queries/add_filter.js.erb
<% (@fields || []).each do |field| %>
<%
  v = @query.available_filters[field]
  next if v.blank?
%>
<%= eq_render_filter_field(@query, field, v) %>
<% end %>

extra_queries/app/views/extra_queries/pinning.js.erb
<% if (params[:pin]) %>
  <% if (@query.eq_pinned?) %>
    RMPlus.EQ.pinning('#query-<%= @query.id %>', false, '<%= url_for({ controller: :extra_queries, action: :pinning, query_id: @query.id }) %>', '<%= l(:eq_title_unpin_query) %>');
  <% end %>
<% else %>
  RMPlus.EQ.pinning('#pinned-query-<%= @query.id %>', true, '<%= url_for({ controller: :extra_queries, action: :pinning, query_id: @query.id, pin: 1 }) %>', '<%= l(:eq_title_pin_query) %>');
<% end %>

extra_queries/app/views/extra_queries/queries/_form.html.erb
<div class="modal-header">
  <a href="#" class="fa fa-times eq-no-line eq-close" data-dismiss="modal" aria-hidden="true"></a>
  <h3><%= @query.new_record? ? l(:label_query_new) : @query.name %></h3>
</div>
<div class="modal-body">
  <% unless @query.eq_editable_by_global_status? %>
    <div class="warning"><%= l(:eq_warning_global_query_editing_from_project, url: url_for(controller: :issues, action: :index, query_id: @query.id)).html_safe %></div>
  <% end %>
  <%= error_messages_for @query %>
  <% if @query.eq_current_project.present? %>
    <%= hidden_field_tag 'current_project_id', @query.eq_current_project.id %>
  <% end %>
  <%= hidden_field_tag 'gantt', '1' if params[:gantt] %>
  <%= hidden_field_tag 'cp_burndown', '1' if params[:cp_burndown] %>
  <% if @query.new_record? %>
    <%= hidden_field_tag 'type', @query.class.name %>
  <% end %>

  <% (@query.filters || {}).each do |k, f| %>
    <%= hidden_field_tag 'f[]', k %>
    <%= hidden_field_tag "op[#{k}]", f[:operator] %>
    <% f[:values] = [f[:values]] if (f[:values].present? || f[:values] == '') && !f[:values].is_a?(Array) %>
    <% (f[:values] || []).each do |v| %>
      <%= hidden_field_tag "v[#{k}][]", v %>
    <% end %>
  <% end %>

  <% @query.sort_criteria.each_with_index do |sort, index| %>
    <%= hidden_field_tag "query[sort_criteria][#{index}][]", sort[0] %>
    <%= hidden_field_tag "query[sort_criteria][#{index}][]", sort[1] %>
  <% end %>

  <% if @query.group_by.present? %>
    <%= hidden_field_tag 'query[group_by]', @query.group_by %>
  <% end %>

  <% (@query.column_names || []).each do |col| %>
    <%= hidden_field_tag 'c[]', col %>
  <% end %>

  <table class="plugin_settings" style="width: 100%">
    <tr>
      <td>
        <label for="query_name"><%=l(:field_name)%></label>
      </td>
      <td>
        <%= text_field 'query', 'name', size: 80 %>
      </td>
    </tr>
    <tr>
      <td>
        <label for="query_category_id"><%= l(:eq_label_query_category) %></label>
      </td>
      <td>
        <%= select_tag('query[category_id]', options_for_select([[]] + QueryCategory.order('name').map { |c| [c.name, c.id] }, @query.category_id), class: 'select2 eq-select2', 'data-combobox' => 'true', 'data-post-url' => Redmine::Utils.relative_url_root + '/query_categories/create_of_query', 'data-model-attribute' => 'name', 'data-select2-width' => '400px') %>
      </td>
    </tr>
    <% if Setting.plugin_extra_queries['custom_query_sidebar_enabled'] && User.current.admin? %>
      <tr>
        <td></td>
        <td>
          <label for="query_eq_pinned">
            <%= check_box_tag('query[eq_pinned]', '1', @query.eq_admin_pinned?) %>
            &mdash;
            <%= l(:eq_label_admin_pin_query) %>
          </label>
        </td>
      </tr>
    <% end %>
    <% if Acl::Settings['enable_ajax_counters'] && User.current.admin? %>
        <tr>
          <td></td>
          <td>
            <label for="query_eq_counter">
              <%= hidden_field_tag('query[eq_counter]', false, id: nil) %>
              <%= check_box_tag('query[eq_counter]', true, @query.eq_counter) %>
              &mdash;
              <%= l(:eq_show_query_counter) %>
            </label>
          </td>
        </tr>
    <% end %>
    <% if User.current.admin? || User.current.allowed_to?(:manage_public_queries, @query.project) %>
      <tr>
        <td>
          <label><%= l(:field_visible) %></label>
        </td>
        <td>
          <div style="margin-bottom: 5px">
            <label style="display: block;"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PRIVATE %> <%= l(:label_visibility_private) %></label>
            <label style="display: block;"><%= radio_button 'query', 'visibility', Query::VISIBILITY_PUBLIC %> <%= l(:label_visibility_public) %></label>
            <label style="display: block;"><%= radio_button 'query', 'visibility', Query::VISIBILITY_ROLES %> <%= l(:label_visibility_roles) %>:</label>
          </div>
          <div id="eq-roles-list">
            <div class='eq-filter-data'>
              <div class="eq-filter-data-list eq-filter-data-item">
                <%= eq_filter_selector(Role.givable.sorted.map { |r| [r.name, r.id] }, selected: @query.roles.map { |it| it.id.to_s }, fullname: 'query[role_ids][]', class: 'eq-columns-list') %>
                <%= hidden_field_tag 'query[role_ids][]', '' %>
              </div>
            </div>
          </div>
        </td>
      </tr>
    <% end %>
    <tr>
      <td></td>
      <td>
        <label for="query_is_for_all">
          <%= check_box_tag 'query_is_for_all', 1, @query.project.nil?, class: (User.current.admin? ? '' : 'disable-unless-private') %>
          &mdash;
          <%= l(:field_is_for_all) %>
        </label>

        <div id="eq-hide-in-projects" style="padding-top: 10px;<%= ' display: none;'.html_safe unless @query.project.nil? %>">
          <%= l(:eq_label_hide_query_for_projects) %>
          <div class='eq-filter-data'>
            <div class="eq-filter-data-list eq-filter-data-item">
              <%= eq_filter_selector(Project.active.order(:name).map { |r| [r.name, r.id] }, selected: @query.eq_hide_in_project_ids, fullname: 'query[hide_in_projects][]', class: 'eq-columns-list') %>
              <%= hidden_field_tag 'query[hide_in_projects][]', '' %>
            </div>
          </div>
        </div>

        <div id="eq-show-in-projects" style="padding-top: 10px;<%= ' display: none;'.html_safe unless @query.project.nil? %>">
          <%= l(:eq_label_show_query_for_projects) %>
          <div class='eq-filter-data'>
            <div class="eq-filter-data-list eq-filter-data-item">
              <%= eq_filter_selector(Project.active.order(:name).map { |r| [r.name, r.id] }, selected: @query.eq_show_in_project_ids, fullname: 'query[show_in_projects][]', class: 'eq-columns-list') %>
              <%= hidden_field_tag 'query[show_in_projects][]', '' %>
            </div>
          </div>
        </div>

        <div id="with_sub_project" style="padding-top: 10px;<%= ' display: none;'.html_safe unless @query.project.nil? %>">
          <label for="query_sub_project">
            <%= check_box_tag 'query[sub_project]', true, @query.sub_project, class: (User.current.admin? ? '' : 'disable-unless-private') %>
            &mdash;
            <%= l(:label_cross_project_descendants) %>
          </label>
        </div>
      </td>
    </tr>

    <tr class="rmp-settings-group">
      <td></td>
      <td>
        <%= l(:label_options) %>
      </td>
    </tr>
    <% if Redmine::Plugin.installed?(:rm_business_time) && params[:cp_burndown].present? %>
      <tr>
        <td></td>
        <td>
          <label>
            <%= check_box_tag 'query[cp_burndown][]', 'cp_burndown_work_off', (@query.cp_burndown || []).include?('cp_burndown_work_off') %>
            &mdash;
            <%= l(:cp_label_burndown_apply_work_off) %>
          </label>
        </td>
      </tr>
    <% end %>

    <% if params[:gantt] %>
      <tr>
        <td>
          <label><%= l(:button_show) %></label>
        </td>
        <td>
          <label class="inline"><%= check_box_tag "query[draw_relations]", "1", @query.draw_relations %> &mdash; <%= t(:label_related_issues) %></label>
          <label class="inline"><%= check_box_tag "query[draw_progress_line]", "1", @query.draw_progress_line %> &mdash; <%= l(:label_gantt_progress_line) %></label>
        </td>
      </tr>
    <% elsif @query.new_record? %>
      <tr>
        <td></td>
        <td>
          <label for="query_default_columns">
            <%= hidden_field_tag 'default_columns', 1 if params[:cp_burndown].present? %>
            <%= check_box_tag 'default_columns', 1, @query.has_default_columns? || params[:cp_burndown].present?, id: 'query_default_columns', disabled: params[:cp_burndown].present? %>
            &mdash;
            <%= l(:label_default_columns) %>
          </label>
        </td>
      </tr>
    <% end %>
    <% if @query.is_a?(IssueQuery) && Redmine::Plugin.installed?(:magic_my_page) %>
      <tr>
        <td><%= l(:label_mmp_legend_for_edit_queries) %></td>
        <td>
          <table>
            <tr>
              <td id="eq-mmp-available-columns">
                <%= l(:description_available_columns) %>
                <%
                   available_columns = eq_query_available_inline_columns_options_for_mm_page(@query)
                   available_columns = query_available_inline_columns_options(@query) if available_columns == []

                   selected_columns = eq_query_selected_inline_columns_options_for_mm_page(@query)
                   selected_columns = query_selected_inline_columns_options(@query) if selected_columns == []

                   available_columns = available_columns - selected_columns
                %>
                <div class='eq-filter-data'>
                  <div class="eq-filter-data-list eq-filter-data-item">
                    <%= eq_filter_selector(available_columns.sort { |x,y| (x[0] || '') <=> (y[0] || '') }, fullname: 'mmp_column_names[]', class: 'eq-columns-list eq-available-columns-container') %>
                  </div>
                </div>
              </td>
              <td style="vertical-align: middle; box-sizing: border-box;">
                <p>
                  <%= link_to('&#8594;'.html_safe, '#', class: 'eq-button eq-add-column', style: 'margin-bottom: 5px;') %>
                </p>
                <p>
                  <%= link_to('&#8592;'.html_safe, '#', class: 'eq-button eq-delete-column') %>
                </p>
              </td>
              <td id="eq-mmp-selected-columns">
                <%= l(:description_selected_columns) %>
                <div class='eq-filter-data'>
                  <div class="eq-filter-data-list eq-filter-data-item">
                    <%= eq_filter_selector(selected_columns, class: 'eq-columns-list eq-columns-container', fullname: 'mmp_column_names[]', id: 'eq-mmp-columns-container') %>
                  </div>
                </div>
              </td>
            </tr>
          </table>
        </td>
      </tr>
    <% end %>
  </table>

</div>
<div class="modal-footer">
  <%= submit_tag l(:button_save), onclick: "$('#eq-mmp-selected-columns [name=\"mmp_column_names[]\"]').prop('checked', true);", disabled: !@query.eq_editable_by_global_status? %>
  <button aria-hidden="true" data-dismiss="modal" style="vertical-align: middle;"><%= l(:eq_label_close_window) %></button>
</div>


<script>
  $(document).ready(function(){
    $("input[name='query[visibility]']").change(function(){
      var roles_checked = $('#query_visibility_1').is(':checked');
      var private_checked = $('#query_visibility_0').is(':checked');
      $("input[name='query[role_ids][]'][type=checkbox]").attr('disabled', !roles_checked);
      if (!private_checked) $("input.disable-unless-private").attr('checked', false);
      $("input.disable-unless-private").attr('disabled', !private_checked);
    }).trigger('change');
  });
  $('#eq-roles-list, #eq-mmp-available-columns, #eq-mmp-selected-columns, #eq-hide-in-projects, #eq-show-in-projects').eq_button({ just_search: true });

  $('#query_is_for_all').change(function() {
    if (this.checked) {
      $('#eq-hide-in-projects').show();
      $('#eq-show-in-projects').show();
      $('#with_sub_project').show();
    } else {
      $('#eq-hide-in-projects').hide();
      $('#eq-show-in-projects').hide();
      $('#with_sub_project').hide();
    }
  });

  RMPlus.Utils.makeSelect2Combobox($('#query_category_id').get(0));
</script>

extra_queries/app/views/extra_queries/queries/edit.html.erb
<%= form_tag(query_path(@query), method: :put, remote: true) do %>
  <%= render partial: 'form' %>
<% end %>

extra_queries/app/views/extra_queries/queries/edit.js.erb
<% if @query.errors.present? %>
  $('#content').find('.flash').remove();
  $('#errorExplanation').remove();

  $('#eq-query-modal').find('.modal-body').prepend('<%= escape_javascript(error_messages_for(@query)) %>');
<% end %>

extra_queries/app/views/extra_queries/queries/new.html.erb
<%= form_tag(@project ? project_queries_path(@project) : queries_path, remote: true) do %>
  <%= render partial: 'form' %>
<% end %>

extra_queries/app/views/extra_queries/queries/new.js.erb
<% if @query.errors.present? %>
  $('#content').find('.flash').remove();
  $('#errorExplanation').remove();

  $('#eq-query-modal').find('.modal-body').prepend('<%= escape_javascript(error_messages_for(@query)) %>');
<% else %>
  $('div.loader').html(' ');
  $(document.body).removeData('ajax_emmiter');
  $('#eq-query-modal').find('input[type="submit"]').removeClass('ajax_hidden_emmiter');


  window.location.href = '<%= eq_redirect_to_issues_path(query_id: @query.id) %>';
<% end %>

extra_queries/app/views/extra_queries/query_group.html.erb
<% if params[:query_group] == 'queries' %>
  <%= eq_render_sidebar_queries(@klass, @project) %>
<% elsif params[:query_group] == 'categories' %>
  <%= eq_render_categories_links(@klass, @project) %>
<% end %>